
default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql12
  username: root
  password: Hachi88%
  host: localhost
  database: protospace_40465_development

test:
  <<: *default
  adapter: mysql12
  username: root
  password: Hachi88%
  host: localhost
  database: protospace_40465_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
